# Site settings
title: METRO.org
email: info@metro.org
description: METRO is a lab where New York's libraries and archives come together to learn, innovate, and collaborate on digital initiatives.
baseurl: "/metro.org"
url: "http://metro.org"

footer:
  address:
    - line: Metropolitan New York Library Council
    - line: 57 East 11th Street, Fourth Floor
    - line: New York, NY 10003
  phone: 212.228.2320
  fax: 212.228.2598

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
- title: twitter
  url: http://twitter.com/mnylc
- title: facebook
  url:
- title: github
  url: http://github.com/mnylc

# Content settings
defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: "/news/:title"
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

# Build settings
markdown: kramdown

# Attribution
image:
  person: "Thomas Hawk"
  url: https://www.flickr.com/photos/thomashawk/10301380936/in/photolist-gGigE9-bBEzTv-dkbajP-r11VHk-8TgY9e-75oLUZ-fP7VXA-5VVrru-6CXPbQ-9TtJAA-bbK4ep-faAxph-edLMAv-6AZ3oV-DgijG-4CMoYu-qdVTXB-zwuK8-qAGCwz-5qAkUi-5sXNuG-6Ty4fJ-BBjzo-5kRG7F-wnJz3r-viokzw-79FB7L-5VqyYX-9RYWQt-f17RHA-rmkAGT-6Praag-aC4p4e-6TmvV7-4KkwTd-5DNEG5-pXtcS-5sN5pF-9DSRqU-4oX5Pu-5sD7xb-8CWehV-Q2DYz-7VjR63-4LnLHt-ojfY6J-niQivN-49km7A-49gi14-cp5fzy
theme:
  person: "Rick Kim"
  name: "agency"
  url: https://github.com/y7kim/agency-jekyll-theme
