- title: 'Digitization Grants'
  url: '/services/digitization-grants/'
  icon: 'money'
  description: ''
- title: 'Delivery Service'
  url: '/services/delivery-service/'
  icon: 'shopping-cart'
  description: ''
- title: 'Referral Cards'
  url: '/services/referral-cards'
  icon: 'credit-card'
  description: ''
- title: 'Photocopy Interchange'
  url: '/services/photocopy-interchange'
  icon: 'exchange'
  description: ''
- title: 'Coordinated Collection Development Aid'
  url: '/services/coordinated-collection-development-aid/'
  icon: 'support'
  description: ''
- title: 'Hospital Library Services'
  url: '/services/hospital-library-services'
  icon: 'hospital-o'
  description: ''
